version: "3"
services:
  webgo_server:
    build:
      context: ../goserver
      dockerfile: Dockerfile_goserver
    image: "goserver"
    container_name: "webgo_server_container"
    restart: always
    ports:
      - "44444:44444"
    volumes:
      - ../goserver/config:/webgo/goserver/config
      - ../goserver/src:/webgo/goserver/src
      - ../webgoRun/server:/webgo/rundata
    depends_on:
      - webgo_mysql
    networks: 
      - server_net
      - mysql_net

  webgo_mysql:
    image: "mysql"
    container_name: "webgo_mysql_container"
    restart: always
    environment:
      MYSQL_DATABASE: "webgo_db"
      MYSQL_USER: 'webgo_user'
      MYSQL_PASSWORD: 'webgo_password'
      MYSQL_ROOT_PASSWORD: "webgo_mysql_password"
    volumes:
      - ../webgoRun/mysql/data:/var/lib/mysql
      - ../webgoRun/mysql/log:/var/log/mysql
      - ../mysql/my.cnf:/etc/my.cnf
      - ../mysql/init:/docker-entrypoint-initdb.d
      - ../mysql/backup:/backup
    entrypoint: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
    ports:
      - "3306:3306"
    networks: 
      - mysql_net

  webgo_nginx:
    image: "nginx"
    container_name: "webgo_nginx_container"
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ../webgoRun/nginx/logs:/usr/local/nginx/logs
      - ../nginx/nginx_default.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
    networks:
      - server_net

networks: 
  server_net:
    name: "server_net"
  mysql_net:
    name: "mysql_net"
      